name: traefik
services:
    traefik:
        extends:
            file: ../../common/traefik/compose.yaml
            service: traefik
        environment:
            ROOT_DOMAINNAME: ${ROOT_DOMAINNAME:?needs root domain name}
