name: traefik
services:
    internal-tailscale-node:
        image: tailscale/tailscale:latest
        hostname: internal-tailscale-node
        container_name: internal-tailscale-node
        environment:
            - TS_AUTHKEY=${HEADSCALE_INTERNAL_AUTHKEY:?needs headscale authkey}
            - TS_EXTRA_ARGS=--advertise-tags=tag:internal --login-server https://headscale.${ROOT_DOMAINNAME}
            - TS_HOSTNAME=internal-media-node
            - TS_STATE_DIR=/var/lib/tailscale
            - TS_USERSPACE=false
            - TS_AUTH_ONCE=true
        volumes:
            - ${APP_ROOT}/tailscale-internal/state:/var/lib/tailscale
        networks:
            - traefik-tailscale
            - socket_proxy
        devices:
            - /dev/net/tun:/dev/net/tun
        cap_add:
            - net_admin
            - sys_module
        restart: unless-stopped

    traefik-tailscale:
        extends:
            file: ../../common/traefik/compose.yaml
            service: traefik

        # make sure this matches headscale/traefik/container/Dockerfile
        image: traefik:3.2.2

        container_name: traefik-tailscale

        security_opt:
            - no-new-privileges:true
        pids_limit: 200
        network_mode: service:internal-tailscale-node
        environment:
            TRAEFIK_PROVIDERS_DOCKER_CONSTRAINTS: "Label(`expose.external`, `false`)"

            TRAEFIK_PROVIDERS_DOCKER_NETWORK: traefik-tailscale

            TRAEFIK_ENTRYPOINTS_WEBSECURE_HTTP_TLS_DOMAINS_0_MAIN: ${INTERNAL_DOMAINNAME:?needs internal domain name}
            TRAEFIK_ENTRYPOINTS_WEBSECURE_HTTP_TLS_DOMAINS_0_SANS: "*.${INTERNAL_DOMAINNAME}"

            ROOT_DOMAINNAME: ${ROOT_DOMAINNAME:?needs root domain name}
        volumes:
            - "${APP_ROOT}/traefik-tailscale/logs:/logs"
            - "${APP_ROOT}/traefik-tailscale/data:/data" # acme.json defined in traefik.yaml

    external-tailscale-node:
        image: tailscale/tailscale:latest
        hostname: external-tailscale-node
        container_name: external-tailscale-node
        environment:
            - TS_AUTHKEY=${HEADSCALE_EXTERNAL_AUTHKEY:?needs headscale authkey}
            - TS_EXTRA_ARGS=--advertise-tags=tag:external --login-server https://headscale.${ROOT_DOMAINNAME}
            - TS_HOSTNAME=external-media-node
            - TS_STATE_DIR=/var/lib/tailscale
            - TS_USERSPACE=false
            - TS_AUTH_ONCE=true
        volumes:
            - ${APP_ROOT}/tailscale-external/state:/var/lib/tailscale
        networks:
            - traefik-tailscale
            - socket_proxy
        devices:
            - /dev/net/tun:/dev/net/tun
        cap_add:
            - net_admin
            - sys_module
        restart: unless-stopped

    traefik-external:
        extends:
            file: ../../common/traefik/compose.yaml
            service: traefik

        image: traefik:3.2.2

        container_name: traefik-external

        network_mode: service:external-tailscale-node

        security_opt:
            - no-new-privileges:true
        pids_limit: 200

        expose:
            - 80
            - 443

        volumes:
            - "${APP_ROOT}/traefik-external/logs:/logs"
            - "${APP_ROOT}/traefik-external/data:/data" # acme.json defined in traefik.yaml

        environment:
            TRAEFIK_PROVIDERS_DOCKER_CONSTRAINTS: "Label(`expose.external`, `true`)"

            TRAEFIK_PROVIDERS_DOCKER_NETWORK: traefik-external

            TRAEFIK_ENTRYPOINTS_WEB_HTTP_REDIRECTIONS_ENTRYPOINT_TO:
            TRAEFIK_ENTRYPOINTS_WEB_HTTP_REDIRECTIONS_ENTRYPOINT_SCHEME:
            TRAEFIK_ENTRYPOINTS_WEBSECURE_ASDEFAULT: false

            ROOT_DOMAINNAME: ${ROOT_DOMAINNAME:?needs root domain name}
