name: traefik
services:
    traefik:
        extends:
            file: ../../common/traefik/compose.yaml
            service: traefik

        # make sure this matches headscale/traefik/container/Dockerfile
        image: traefik:3.2.2

        security_opt:
            - no-new-privileges:true
        pids_limit: 200
        environment:
            ROOT_DOMAINNAME: ${ROOT_DOMAINNAME:?needs root domain name}
