name: traefik
services:
    tailscale-node:
        image: tailscale/tailscale:latest
        hostname: tailscale-node
        container_name: tailscale-node
        environment:
            - TS_AUTHKEY=${HEADSCALE_AUTHKEY:?needs headscale authkey}
            - TS_EXTRA_ARGS=--advertise-tags=tag:subserver --login-server https://headscale.${ROOT_DOMAINNAME}
            - TS_HOSTNAME=media-node
            - TS_STATE_DIR=/var/lib/tailscale
            - TS_USERSPACE=false
        volumes:
            - ${PWD}/tailscale-nginx/state:/var/lib/tailscale
        networks:
            - traefik-tailscale
            - socket_proxy
        devices:
            - /dev/net/tun:/dev/net/tun
        cap_add:
            - net_admin
            - sys_module
        restart: unless-stopped

    traefik-tailscale:
        extends:
            file: ../../common/traefik/compose.yaml
            service: traefik

        # make sure this matches headscale/traefik/container/Dockerfile
        image: traefik:3.2.2

        container_name: traefik-tailscale

        security_opt:
            - no-new-privileges:true
        pids_limit: 200
        network_mode: service:tailscale-node
        environment:
            TRAEFIK_PROVIDERS_DOCKER_CONSTRAINTS: "Label(`expose.external`, `false`)"

            TRAEFIK_PROVIDERS_DOCKER_NETWORK: traefik-tailscale

            TRAEFIK_ENTRYPOINTS_WEBSECURE_HTTP_TLS_DOMAINS_0_MAIN: ${INTERNAL_DOMAINNAME:?needs internal domain name}
            TRAEFIK_ENTRYPOINTS_WEBSECURE_HTTP_TLS_DOMAINS_0_SANS: "*.${INTERNAL_DOMAINNAME}"

            ROOT_DOMAINNAME: ${ROOT_DOMAINNAME:?needs root domain name}
        labels:
            traefik.http.routers.traefik-rtr.rule: Host(`traefik.${DOMAINNAME}`)

    traefik-external:
        extends:
            file: ../../common/traefik/compose.yaml
            service: traefik

        # make sure this matches headscale/traefik/container/Dockerfile
        image: traefik:3.2.2

        container_name: traefik-external

        networks:
            - traefik-external
            - socket_proxy

        security_opt:
            - no-new-privileges:true
        pids_limit: 200

        expose:
            - 80
            - 443

        environment:
            TRAEFIK_PROVIDERS_DOCKER_CONSTRAINTS: "Label(`expose.external`, `true`)"

            TRAEFIK_PROVIDERS_DOCKER_NETWORK: traefik-external

            ROOT_DOMAINNAME: ${ROOT_DOMAINNAME:?needs root domain name}
