# extends the common traefik with TLS config,
# since this is the primary reverse proxy

services:
    traefik:
        extends:
            file: ../../common/traefik/compose.yaml
            service: traefik
        build:
            context: ./container
        container_name: traefik
        networks:
            - traefik
            - socket_proxy
        ports:
            - 80:80
            - 443:443
        environment:
            PROXY_SUBDOMAINS: ${PROXY_SUBDOMAINS:?needs proxy subdomains}

            ROOT_DOMAINNAME: ${DOMAINNAME:?needs domain name}

            # heh... this looks disgusting
