# extends the common traefik with TLS config,
# since this is the primary reverse proxy

services:
    traefik:
        extends:
            file: ../../common/traefik/compose.yaml
            service: traefik
        container_name: traefik
        networks:
            - traefik
            - socket_proxy
        ports:
            - 80:80
            - 443:443
        volumes:
            - "${APP_ROOT}/traefik/logs:/logs"
            - "${APP_ROOT}/traefik/data:/data" # acme.json defined in traefik.yaml
            - "${APP_ROOT}/traefik/plugins:/plugins-storage"
            - ./ban.html:/ban.html
        environment:
            PROXY_SUBDOMAINS: ${PROXY_SUBDOMAINS:?needs proxy subdomains}

            ROOT_DOMAINNAME: ${DOMAINNAME:?needs domain name}

            # TRAEFIK_EXPERIMENTAL_PLUGINS_BOUNCER_MODULENAME: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
            # TRAEFIK_EXPERIMENTAL_PLUGINS_BOUNCER_VERSION: v1.3.5

            # CROWDSEC_API_KEY: ${CROWDSEC_BOUNCER_LAPI_KEY}

            # TRAEFIK_ENTRYPOINTS_WEBSECURE_HTTP_MIDDLEWARES: >-
            #     middlewares-rate-limit@file,
            #     middlewares-compress@file,
            #     middlewares-secure-headers@file,
            #     middlewares-crowdsec@file
