# extends the common traefik with TLS config,
# since this is the primary reverse proxy

services:
    traefik:
        extends:
            file: ../../common/traefik/compose.yaml
            service: traefik
        build:
            context: ./container
        container_name: traefik
        networks:
            - traefik
            - socket_proxy
        ports:
            - 80:80
            - 443:443
        environment:
            PROXY_SUBDOMAINS: ${PROXY_SUBDOMAINS:?needs proxy subdomains}

            ROOT_DOMAINNAME: ${DOMAINNAME:?needs domain name}

            # heh... this looks disgusting

            # http -> https redirect
            TRAEFIK_ENTRYPOINTS_WEB_HTTP_REDIRECTIONS_ENTRYPOINT_TO: websecure
            TRAEFIK_ENTRYPOINTS_WEB_HTTP_REDIRECTIONS_ENTRYPOINT_SCHEME: https

            TRAEFIK_ENTRYPOINTS_WEBSECURE_ADDRESS: ":443"
            TRAEFIK_ENTRYPOINTS_WEBSECURE_ASDEFAULT: true

            # general middlewares
            TRAEFIK_ENTRYPOINTS_WEBSECURE_HTTP_MIDDLEWARES: >-
                middlewares-rate-limit@file,
                middlewares-compress@file,
                middlewares-secure-headers@file

            TRAEFIK_ENTRYPOINTS_WEBSECURE_HTTP_TLS_OPTIONS: "tls-opts@file"
            TRAEFIK_ENTRYPOINTS_WEBSECURE_HTTP_TLS_CERTRESOLVER: "le"

            # acme challenge domain
            TRAEFIK_ENTRYPOINTS_WEBSECURE_HTTP_TLS_DOMAINS_0_MAIN: ${DOMAINNAME:?needs domain name}

            # modified by init.sh
            TRAEFIK_ENTRYPOINTS_WEBSECURE_HTTP_TLS_DOMAINS_0_SANS: "*.${DOMAINNAME:?needs domain name}"

            # allowed IPs for forwarded headers
            # Cloudflare and local networks
            TRAEFIK_ENTRYPOINTS_WEBSECURE_FORWARDEDHEADERS_TRUSTEDIPS: >-
                173.245.48.0/20,
                103.21.244.0/22,
                103.22.200.0/22,
                103.31.4.0/22,
                141.101.64.0/18,
                108.162.192.0/18,
                190.93.240.0/20,
                188.114.96.0/20,
                197.234.240.0/22,
                198.41.128.0/17,
                162.158.0.0/15,
                104.16.0.0/13,
                104.24.0.0/14,
                172.64.0.0/13,
                131.0.72.0/22,
                127.0.0.1/32,
                10.0.0.0/8,
                192.168.0.0/16,
                172.16.0.0/12

            TRAEFIK_CERTIFICATESRESOLVERS_LE_ACME_EMAIL: ${CF_API_EMAIL?needs cloudflare email}

            CF_API_EMAIL: ${CF_API_EMAIL:?needs cloudflare email}
            CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN:?needs cloudflare dns token}
