services:
    headscale:
        image: headscale/headscale:stable
        container_name: headscale
        user: ${PUID}:${PGID}
        volumes:
            - ../headscale/config:/etc/headscale
            - ../${APP_ROOT}/headscale/data:/var/lib/headscale
            - ../${APP_ROOT}/headscale/sock:/var/run/headscale
        networks:
            - traefik
            - headscale
        environment:
            - HEADSCALE_SERVER_URL=https://headscale.${DOMAINNAME}

            - HEADSCALE_DNS_BASE_DOMAIN=m.${DOMAINNAME}

            - HEADSCALE_OIDC_CLIENT_ID=${HEADSCALE_OIDC_CLIENT_ID:?err}
            - HEADSCALE_OIDC_CLIENT_SECRET=${HEADSCALE_OIDC_CLIENT_SECRET:?err}
            - HEADSCALE_OICD_ISSUER=${HEADSCALE_OICD_ISSUER:?err}
        command: serve
        restart: unless-stopped
        expose:
            - 8080
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.headscale-rtr.rule=Host(`headscale.${DOMAINNAME}`)"

    headplane:
        container_name: headplane
        image: ghcr.io/tale/headplane:0.3.9
        restart: unless-stopped
        volumes:
            - "../${APP_ROOT}/headscale/data:/var/lib/headscale"
            - "../headscale/config:/etc/headscale"
        environment:
            # This is always required for Headplane to work
            COOKIE_SECRET: "${HEADPLANE_COOKIE_SECRET:?headplane_cookie_secret is required}"

            DOCKER_SOCK: "tcp://socket-proxy:2375"
            HEADSCALE_INTEGRATION: "docker"
            HEADSCALE_CONTAINER: "headscale"
            DISABLE_API_KEY_LOGIN: "true"
            HOST: "0.0.0.0"
            PORT: "3000"

            # Only set this to false if you aren't behind a reverse proxy
            COOKIE_SECURE: "true"
        expose:
            - 3000
        networks:
            - traefik
            - headscale
            - socket_proxy
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.headplane-rtr.rule=Host(`headscale.${DOMAINNAME}`) && PathPrefix(`/admin`)"
            ## Middlewares
            - "traefik.http.routers.headplane-rtr.middlewares=middlewares-authentik@file"
