services:
    headscale:
        image: headscale/headscale:stable
        container_name: headscale
        user: ${PUID}:${PGID}
        volumes:
            - ../headscale/config:/etc/headscale
            - ../${APP_ROOT}/headscale/data:/var/lib/headscale
            - ../${APP_ROOT}/headscale/sock:/var/run/headscale
        networks:
            - traefik
        command: serve
        restart: unless-stopped
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.headscale-rtr.rule=Host(`headscale.${DOMAINNAME}`)"
            - "traefik.http.services.headscale-rtr.loadbalancer.server.port=8080"
    headscale-ui:
        image: ghcr.io/gurucomputing/headscale-ui:latest
        restart: unless-stopped
        container_name: headscale-ui
        networks:
            - traefik
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.headscale-ui-rtr.rule=Host(`headscale.${DOMAINNAME}`) && PathPrefix(`/web`)"
