services:
    headscale:
        image: headscale/headscale:stable
        container_name: headscale
        user: ${PUID}:${PGID}
        volumes:
            - ../headscale/config:/etc/headscale
            - ../${APP_ROOT}/headscale/data:/var/lib/headscale
            - ../${APP_ROOT}/headscale/sock:/var/run/headscale
        networks:
            - traefik
        command: serve
        restart: unless-stopped
        expose:
            - 8080
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.headscale-rtr.rule=Host(`headscale.${DOMAINNAME}`)"
    headscale-ui:
        image: ghcr.io/gurucomputing/headscale-ui:latest
        restart: unless-stopped
        container_name: headscale-ui
        volumes:
            - "../headscale/config/ui:/data"
        networks:
            - traefik
        expose:
            - 8080
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.headscale-ui-rtr.rule=Host(`headscale.${DOMAINNAME}`) && PathPrefix(`/web`)"
            - "traefik.http.services.headscale-ui-svc.loadbalancer.server.port=8080"
