services:
    frps:
        image: snowdreamtech/frps
        container_name: frps
        user: ${PUID}:${PGID}
        network_mode: host
        volumes:
            - ../frp/config:/etc/frp
        restart: unless-stopped
        environment:
            - FRP_OIDC_ISSUER=${FRP_OIDC_ISSUER:?err}
            - FRP_OIDC_AUDIENCE=${FRP_OIDC_AUDIENCE:?err}

        # traefik config in traefik config file
