services:
    tailscale-exit-node:
        build:
            context: ./container

        container_name: tailscale-exit-node
        environment:
            - TS_EXTRA_ARGS=--advertise-tags=tag:container --advertise-exit-node
            - TS_HOSTNAME=windscribe
            - TS_STATE_DIR=/var/lib/tailscale
            - TS_USERSPACE=true
            - HEADSCALE_HOST=10.125.0.81:8080
        volumes:
            - ../${APP_ROOT}/tailscale/data:/var/lib/tailscale
            - ../${APP_ROOT}/tailscale/logs:/logs
            # headscale stuff
            - ../headscale/config:/etc/headscale
            - ../${APP_ROOT}/headscale/data:/var/lib/headscale
            - ../${APP_ROOT}/headscale/sock:/var/run/headscale
        depends_on:
            - headscale
        network_mode: service:gluetun
        restart: unless-stopped

    gluetun:
        image: qmcgaw/gluetun
        container_name: gluetun
        cap_add:
            - NET_ADMIN
        devices:
            - /dev/net/tun:/dev/net/tun
        networks:
            - headscale
        environment:
            - VPN_SERVICE_PROVIDER=${WIREGUARD_PROVIDER}

            - VPN_TYPE=wireguard
            - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
            - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
            - WIREGUARD_PRESHARED_KEY=${WIREGUARD_PRESHARED_KEY}

            # IMPORTANT FOR SPEEDS
            - SERVER_CITIES=${WIREGUARD_SERVER_CITIES}
