http:
    listeners:
        - name: web
          resources:
              - name: discovery
              - name: human
              - name: oauth
              - name: compat
              - name: graphql
              - name: assets
          binds:
              - address: "[::]:8080"
          proxy_protocol: false
    trusted_proxies:
        - 192.168.0.0/16
        - 172.16.0.0/12
        - 10.0.0.0/10
        - 127.0.0.1/8
        - fd00::/8
        - ::1/128
    public_base: http://[::]:8080/
    issuer: http://[::]:8080/
database:
    uri: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}
    max_connections: 10
    min_connections: 0
    connect_timeout: 30
    idle_timeout: 600
    max_lifetime: 1800
email:
    from: '"Authentication Service" <root@localhost>'
    reply_to: '"Authentication Service" <root@localhost>'
    transport: blackhole
secrets:
    # This must be a 32-byte long hex-encoded key
    encryption: ${ENCRYPTION_KEY}
    keys:
        - kid: ${KEY_1_KID}
          key: |
${KEY_1_RSA_KEY}

        - kid: ${KEY_2_KID}
          key: |
${KEY_2_EC_KEY}

        - kid: ${KEY_3_KID}
          key: |
${KEY_3_EC_KEY}

passwords:
    enabled: false

clients:
    - client_id: 0000000000000000000SYNAPSE
      client_auth_method: client_secret_basic
      client_secret: ${CLIENT_BASIC_SECRET}

matrix:
    homeserver: ${DOMAINNAME}
    secret: ${ADMIN_BASIC_SECRET}
    endpoint: http://matrix:8008
