http:
    listeners:
        - name: web
          resources:
              - name: discovery
              - name: human
              - name: oauth
              - name: compat
              - name: graphql
              - name: assets
          binds:
              - address: "[::]:8080"
          proxy_protocol: false
    trusted_proxies:
        - 192.168.0.0/16
        - 172.16.0.0/12
        - 10.0.0.0/10
        - 127.0.0.1/8
        - fd00::/8
        - ::1/128
    public_base: https://matrix-auth.${DOMAINNAME}/
    issuer: https://${DOMAINNAME}/
database:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    port: 5432
    database: ${POSTGRES_DB}
    host: ${POSTGRES_HOST}
    max_connections: 10
    min_connections: 0
    connect_timeout: 30
    idle_timeout: 600
    max_lifetime: 1800
email:
    from: '"Authentication Service" <root@localhost>'
    reply_to: '"Authentication Service" <root@localhost>'
    transport: blackhole
secrets:
    # This must be a 32-byte long hex-encoded key
    encryption: ${ENCRYPTION_KEY}
    keys:
        - kid: ${KEY_1_KID}
          key: |
${KEY_1_RSA_KEY}

        - kid: ${KEY_2_KID}
          key: |
${KEY_2_EC_KEY}

        - kid: ${KEY_3_KID}
          key: |
${KEY_3_EC_KEY}

upstream_oauth2:
  providers:
    - id: 01JG41VCS517HEQTFXXY83N5GF
      human_name: Authentik
      issuer: ${OIDC_ISSUER_URL} # TO BE FILLED
      client_id: ${OIDC_CLIENT_ID} # TO BE FILLED
      client_secret: ${OIDC_CLIENT_SECRET} # TO BE FILLED
      token_endpoint_auth_method: client_secret_basic
      scope: "openid profile email"
      claims_imports:
        localpart:
          action: require
          template: "{{ user.preferred_username }}"
        displayname:
          action: suggest
          template: "{{ user.name }}"
        email:
          action: ignore
          template: "{{ user.preferred_username }}@${DOMAINNAME}"
          set_email_verification: always


passwords:
    enabled: false

clients:
    - client_id: 0000000000000000000SYNAPSE
      client_auth_method: client_secret_basic
      client_secret: ${CLIENT_BASIC_SECRET}

matrix:
    homeserver: ${DOMAINNAME}
    secret: ${ADMIN_BASIC_SECRET}
    endpoint: http://matrix:8008
