name: whitelist_domain_root
description: "Whitelist events from private ipv4 addresses"
whitelist:
    reason: "don't ban when server goes down"

    expression:
        - "evt.Meta.traefik_router_name == 'homepage-rtr@docker'"
