services:
    headscale:
        image: headscale/headscale:stable
        container_name: headscale
        user: ${PUID}:${PGID}
        security_opt:
            - no-new-privileges:true
        pids_limit: 200
        volumes:
            - ./config:/etc/headscale
            - ${APP_ROOT}/headscale/data:/var/lib/headscale
            - ${APP_ROOT}/headscale/sock:/var/run/headscale
        networks:
            - traefik
            - headscale
        environment:
            HEADSCALE_SERVER_URL: https://headscale.${DOMAINNAME}

            HEADSCALE_DNS_BASE_DOMAIN: m.${DOMAINNAME}

            HEADSCALE_OIDC_CLIENT_ID: ${HEADSCALE_OIDC_CLIENT_ID}
            HEADSCALE_OIDC_CLIENT_SECRET: ${HEADSCALE_OIDC_CLIENT_SECRET}
            HEADSCALE_OIDC_ISSUER: ${HEADSCALE_OIDC_ISSUER}
        command: serve
        restart: unless-stopped
        depends_on:
            - authentik_server
            - traefik
        expose:
            - 8080
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.headscale-rtr.rule=Host(`headscale.${DOMAINNAME}`)"

    headplane:
        build:
            context: ./container
        user: ${PUID}:${PGID}
        security_opt:
            - no-new-privileges:true
        pids_limit: 200
        container_name: headplane
        restart: unless-stopped
        volumes:
            - ./config:/etc/headscale
            - ${APP_ROOT}/headscale/data:/var/lib/headscale
            - ${APP_ROOT}/headscale/sock:/var/run/headscale
            - ${APP_ROOT}/headplane/cache:/var/cache/headplane
        depends_on:
            - headscale
        environment:
            HEADSCALE_PUBLIC_URL: https://headscale.${DOMAINNAME}
            HEADSCALE_URL: http://headscale:8080

            OIDC_CLIENT_ID: ${HEADPLANE_OIDC_CLIENT_ID}
            OIDC_CLIENT_SECRET: ${HEADPLANE_OIDC_CLIENT_SECRET}
            OIDC_ISSUER: ${HEADPLANE_OIDC_ISSUER}

            # This is always required for Headplane to work
            COOKIE_SECRET: "${HEADPLANE_COOKIE_SECRET:?headplane_cookie_secret is required}"

            DOCKER_SOCK: "tcp://socket-proxy:2375"
            HEADSCALE_INTEGRATION: "docker"
            HEADSCALE_CONTAINER: "headscale"
            DISABLE_API_KEY_LOGIN: "true"
            HOST: "0.0.0.0"
            PORT: "3000"

            # Only set this to false if you aren't behind a reverse proxy
            COOKIE_SECURE: "true"
        expose:
            - 3000
        networks:
            - traefik
            - headscale
            - socket_proxy
        labels:
            traefik.enable: true
            traefik.http.routers.headplane-rtr.rule: Host(`headscale.${DOMAINNAME}`) && PathPrefix(`/admin`)

            homepage.group: internal
            homepage.name: Headscale
            homepage.icon: sh-headscale.svg
            homepage.href: https://headscale.${DOMAINNAME}/admin
