services:
    headscale:
        image: headscale/headscale:0.26.0
        container_name: headscale
        user: ${PUID}:${PGID}
        security_opt:
            - no-new-privileges:true
        pids_limit: 200
        volumes:
            - ./config/headscale:/etc/headscale
            - ${APP_ROOT}/headscale/data:/var/lib/headscale
            - ${APP_ROOT}/headscale/sock:/var/run/headscale
        networks:
            - traefik
            - headscale
        environment:
            HEADSCALE_SERVER_URL: https://headscale.${DOMAINNAME}

            HEADSCALE_DNS_BASE_DOMAIN: m.${DOMAINNAME}

            HEADSCALE_OIDC_CLIENT_ID: ${HEADSCALE_OIDC_CLIENT_ID}
            HEADSCALE_OIDC_CLIENT_SECRET: ${HEADSCALE_OIDC_CLIENT_SECRET}
            HEADSCALE_OIDC_ISSUER: ${HEADSCALE_OIDC_ISSUER}

            PROXY_SUBDOMAINS: ${PROXY_SUBDOMAINS}
            DOMAINNAME: ${DOMAINNAME}
        command: serve
        restart: unless-stopped
        depends_on:
            - authentik_server
            - traefik
        expose:
            - 8080
        labels:
            traefik.enable: true
            traefik.http.routers.headscale-rtr.rule: Host(`headscale.${DOMAINNAME}`)
            # This is needed for Headplane to find it and signal it
            me.tale.headplane.target: headscale

    headplane:
        image: ghcr.io/tale/headplane:0.6.0
        user: ${PUID}:${PGID}
        security_opt:
            - no-new-privileges:true
        pids_limit: 200
        container_name: headplane
        restart: unless-stopped
        volumes:
            - "./config/headscale:/etc/headscale"
            - "./config/headplane:/etc/headplane"

            # Headplane stores its data in this directory
            - "${APP_ROOT}/headplane/data:/var/lib/headplane"
        depends_on:
            - headscale
        environment:
            HEADPLANE_HEADSCALE__URL: https://headscale.${DOMAINNAME}

            HEADPLANE_OIDC__CLIENT_ID: ${HEADPLANE_OIDC_CLIENT_ID}
            HEADPLANE_OIDC__CLIENT_SECRET: ${HEADPLANE_OIDC_CLIENT_SECRET}
            HEADPLANE_OIDC__ISSUER: ${HEADPLANE_OIDC_ISSUER}

            HEADPLANE_OIDC__REDIRECT_URI: https://headscale.${DOMAINNAME}/admin/oidc/callback

            # This is always required for Headplane to work
            HEADPLANE_SERVER__COOKIE_SECRET: "${HEADPLANE_COOKIE_SECRET:?headplane_cookie_secret is required}"

            HEADPLANE_OIDC__HEADSCALE_API_KEY: "${HEADSCALE_API_KEY}"
            HEADPLANE_INTEGRATION_AGENT__PRE_AUTHKEY: "${HEADPLANE_AGENT_PREAUTH_KEY}"

            DOCKER_SOCK: "tcp://socket-proxy:2375"

            HEADPLANE_LOAD_ENV_OVERRIDES: true
        expose:
            - 3000
        networks:
            - traefik
            - headscale
            - socket_proxy
        labels:
            traefik.enable: true
            traefik.http.routers.headplane-rtr.rule: Host(`headscale.${DOMAINNAME}`) && PathPrefix(`/admin`)
            ## Middlewares
            traefik.http.routers.headplane-rtr.middlewares: middlewares-authentik@file
            homepage.group: internal
            homepage.name: Headscale
            homepage.icon: sh-headscale.svg
            homepage.href: https://headscale.${DOMAINNAME}/admin
