services:
    watchtower:
        image: containrrr/watchtower:latest
        container_name: watchtower
        user: ${PUID}:${PGID}
        networks:
            - socket_proxy
        environment:
            DOCKER_HOST: tcp://socket-proxy:2375
            WATCHTOWER_NOTIFICATION_URL: ${WATCHTOWER_NOTIFICATION_URL:?err}
            WATCHTOWER_POLL_INTERVAL: 86400
            WATCHTOWER_INCLUDE_RESTARTING: true
            # see https://github.com/containrrr/watchtower/issues/1050
            WATCHTOWER_WARN_ON_HEAD_FAILURE: never
# must add a depends-on clause to socket-proxy in extended config
