include:
    # common
    - ../common/socket-proxy/compose.yaml

    # traefik and watchtower cuz they're special
    - ./traefik/compose.yaml
    - ./watchtower/compose.yaml

    # more specials
    - ./homepage/compose.yaml
    - ./headscale/compose.yaml
    - ./exit-node/compose.yaml
    - ./frps/compose.yaml
    - ./authentik/compose.yaml
    - ./mattermost/compose.yaml

networks:
    socket_proxy:
        driver: bridge

    socket_proxy_writable:
        driver: bridge

    traefik:
        name: traefik
        driver: bridge

    headscale:
        driver: bridge
