include:
    # common
    - ../common/socket-proxy/compose.yaml

    # traefik and watchtower cuz they're special
    - ./traefik/compose.yaml
    - ./watchtower/compose.yaml

    # more specials
    - ./homepage/compose.yaml
    - ./headscale/compose.yaml
    - ./exit-node/compose.yaml
    - ./frps/compose.yaml
    - ./actual-budget/compose.yaml
    - ./authentik/compose.yaml
    - ./matrix/compose.yaml
    - ./static/compose.yaml
    - ./mealie/compose.yaml
    - ./pingvin/compose.yaml
    - ./immich/compose.yaml
    # - ./crowdsec/compose.yaml

networks:
    socket_proxy:
        driver: bridge

    socket_proxy_writable:
        driver: bridge

    traefik:
        name: traefik
        driver: bridge
        ipam:
            config:
                - subnet: 10.120.0.0/24

    headscale:
        driver: bridge
