http:
    middlewares:
        middlewares-crowdsec:
            plugin:
                bouncer:
                    enabled: true
                    crowdsecLapiKey: '{{ env "CROWDSEC_API_KEY" }}'
