http:
    middlewares:
        middlewares-crowdsec:
            plugin:
                bouncer:
                    enabled: true
                    crowdsecLapiKey: '{{ env "CROWDSEC_API_KEY" }}'
                    logLevel: DEBUG
                    updateIntervalSeconds: 60

                    updateMaxFailure: 0
                    defaultDecisionSeconds: 60
                    httpTimeoutSeconds: 10
                    crowdsecMode: live
                    crowdsecAppsecEnabled: false
                    crowdsecAppsecHost: crowdsec:7422
                    crowdsecAppsecFailureBlock: false
                    crowdsecAppsecUnreachableBlock: false
                    crowdsecLapiHost: crowdsec:8080
                    crowdsecLapiScheme: http
                    crowdsecLapiTLSInsecureVerify: false
                    crowdsecCapiScenarios:
                        - crowdsecurity/http-path-traversal-probing
                        - crowdsecurity/http-xss-probing
                        - crowdsecurity/http-generic-bf
                    forwardedHeadersTrustedIPs:
                        - 173.245.48.0/20
                        - 103.21.244.0/22
                        - 103.22.200.0/22
                        - 103.31.4.0/22
                        - 141.101.64.0/18
                        - 108.162.192.0/18
                        - 190.93.240.0/20
                        - 188.114.96.0/20
                        - 197.234.240.0/22
                        - 198.41.128.0/17
                        - 162.158.0.0/15
                        - 104.16.0.0/13
                        - 104.24.0.0/14
                        - 172.64.0.0/13
                        - 131.0.72.0/22
                        - 127.0.0.1/32
                        - 10.0.0.0/8
                        - 192.168.0.0/16
                        - 172.16.0.0/12
                        - 10.0.10.23/32
                        - 10.0.20.0/24
                    clientTrustedIPs:
                        - 192.168.1.0/24
                    forwardedHeadersCustomName: X-Custom-Header
                    remediationHeadersCustomName: cs-remediation
                    redisCacheEnabled: false
