services:
    cinny-config:
        image: alpine:latest
        container_name: cinny-config
        user: ${PUID}:${PGID}
        entrypoint: ["/bin/sh", "/usr/local/bin/init.sh"]
        volumes:
            - ./config/config.template.json:/config.template.json
            - ${APP_ROOT}/cinny/config:/app

            - ./container/init.sh:/usr/local/bin/init.sh
        restart: no
        environment:
            DOMAINNAME: ${DOMAINNAME}

    cinny:
        image: ghcr.io/cinnyapp/cinny:latest
        container_name: cinny

        user: ${PUID}:${PGID}
        volumes:
            - ./config/config.template.json:/config.template.json
            # this allows the config.json file to be writable by the runtime user
            - ${APP_ROOT}/cinny/config/config.json:/app/config.json

        depends_on:
            cinny-config:
                condition: service_completed_successfully
