services:
    cinny-config:
        image: alpine:latest
        container_name: cinny-config
        entrypoint: ["/bin/sh", "-c"]
        command: |
            (
                echo "cat <<EOF"
                cat /config.template.json
                echo EOF
            ) | sh >/app/config.json
        volumes:
            - ./config/config.template.json:/config.template.json
            - ${APP_ROOT}/cinny/config:/app
        restart: no

    cinny:
        image: ghcr.io/cinnyapp/cinny:latest
        container_name: cinny

        user: ${PUID}:${PGID}
        volumes:
            - ./config/config.template.json:/config.template.json
            # this allows the config.json file to be writable by the runtime user
            - ${APP_ROOT}/cinny/config/config.json:/app/config.json

        depends_on:
            cinny-config:
                condition: service_completed_successfully

        environment:
            DOMAINNAME: ${DOMAINNAME}
