services:
    cinny-config:
        image: alpine:latest
        container_name: cinny-config
        user: ${PUID}:${PGID}
        entrypoint: ["/bin/sh", "/usr/local/bin/init.sh"]
        volumes:
            - ./config/config.template.json:/config.template.json
            - ${APP_ROOT}/cinny/config:/app

            - ./container/init.sh:/usr/local/bin/init.sh
        network_mode: none
        restart: no
        environment:
            DOMAINNAME: ${DOMAINNAME}

    cinny:
        image: ghcr.io/cinnyapp/cinny:latest
        container_name: cinny

        volumes:
            - ./config/config.template.json:/config.template.json
            # this allows the config.json file to be writable by the runtime user
            - ${APP_ROOT}/cinny/config/config.json:/app/config.json
            # likewise
            - ${APP_ROOT}/cinny/nginx/cache:/var/cache/nginx
            - ${APP_ROOT}/cinny/nginx/ryb:/var/log/nginx

        networks:
            - traefik

        depends_on:
            cinny-config:
                condition: service_completed_successfully

        labels:
            traefik.enable: true
            traefik.http.routers.cinny-rtr.rule: Host(`cinny.${DOMAINNAME}`)
            homepage.group: stuff
            homepage.name: Cinny
            homepage.href: https://cinny.${DOMAINNAME}
            homepage.icon: mdi-forum
