services:
    mealie:
        image: ghcr.io/mealie-recipes/mealie:v2.8.0
        container_name: mealie
        user: ${PUID}:${PGID}
        security_opt:
            - no-new-privileges:true
        restart: unless-stopped
        volumes:
            - ${APP_ROOT}/mealie/data:/app/data
            - ${APP_ROOT}/mealie/nltk_data:/nltk_data
        deploy:
            resources:
                limits:
                    pids: 200
                    memory: 1000M #

        networks:
            - traefik

        environment:
            # Set Backend ENV Variables Here
            ALLOW_SIGNUP: "false"
            ALLOW_PASSWORD_LOGIN: "false"
            OIDC_AUTH_ENABLED: "true"
            OIDC_CLIENT_ID: ${MEALIE_OIDC_CLIENT_ID}
            OIDC_CLIENT_SECRET: ${MEALIE_OIDC_CLIENT_SECRET}
            OIDC_PROVIDER_NAME: "Authentik"
            OIDC_CONFIGURATION_URL: https://authentik.${DOMAINNAME}/application/o/mealie/.well-known/openid-configuration
            PUID: ${PUID}
            PGID: ${PGID}
            TZ: ${TZ}
            BASE_URL: https://mealie.${DOMAINNAME}
        expose:
            - 9000

        labels:
            traefik.enable: true

            traefik.http.routers.mealie-rtr.rule: Host(`mealie.${DOMAINNAME}`)

            homepage.group: stuff
            homepage.name: Mealie
            homepage.icon: sh-mealie.svg
            homepage.href: https://mealie.${DOMAINNAME}
