networks:
    arrs:
        driver: bridge
        ipam:
            config:
                - subnet: 10.125.0.0/24

    jellyfin:
        driver: bridge

    socket_proxy:
        name: socket_proxy
        driver: bridge
        ipam:
            config:
                - subnet: 172.16.224.0/24

    traefik:
        name: traefik
        driver: bridge
        ipam:
            config:
                - subnet: 10.255.224.0/24

include:
    # common
    - ../common/socket-proxy/compose.yaml
    - ../common/homepage/compose.yaml
    - ../common/watchtower/compose.yaml

    - ./frpc/compose.yaml
    - ./arrs/compose.yaml
    - ./downloader/compose.yaml
    - ./view/compose.yaml
    - ./traefik/compose.yaml
