services:
    # media upload solution
    # rclone:
    #     container_name: rclone
    #     # image: rclone/rclone # or ghcr.io/wiserain/rclone
    #     restart: unless-stopped
    #     network_mode: "bridge"
    #     build:
    #         context: ./rclone/rclone
    #     volumes:
    #         - ./rclone/config:/config/rclone
    #         - ./rclone/log:/log
    #         - ./rclone/cache:/cache
    #         - ./rclone/scripts:/scripts
    #         - ./remotes:/mnt:rshared
    #     devices:
    #         - /dev/fuse:/dev/fuse:rwm
    #     cap_add:
    #         - SYS_ADMIN
    #     security_opt:
    #         - apparmor:unconfined
    #     healthcheck:
    #         test: ["CMD-SHELL", "ls /mnt/onedrive/downloads"]
    #     environment:
    #         - PUID=${PUID}
    #         - PGID=${PGID}
    #         - TZ=${TZ:-Etc/UTC}

    #     entrypoint: "/bin/sh /scripts/init.sh"

    ### user facing ###

    # jellyseerr and jellyfin have custom themes--no themepark needed
    jellyseerr:
        image: fallenbagel/jellyseerr:latest
        container_name: jellyseerr
        user: ${PUID}:${PGID}
        environment:
            - LOG_LEVEL=info
            - TZ=${TZ:-Etc/UTC}
        ports:
            - 5055:5055
        volumes:
            - ${APP_ROOT}/jellyseerr/app/config:/app/config
        networks:
            - jellyfin
            - arrs
        restart: unless-stopped

    jellyfin:
        image: jellyfin/jellyfin
        container_name: jellyfin
        user: ${PUID}:${PGID}
        environment:
            - TZ=${TZ:-Etc/UTC}
            - JELLYFIN_PublishedServerUrl=https://${DOMAINNAME}
        volumes:
            - ${APP_ROOT}/jellyfin/config:/config
            - ${APP_ROOT}/jellyfin/cache:/cache
            - /dev/dri/renderD128:/dev/dri/renderD128
            - ./remotes:/remotes:rshared
        depends_on:
            []
            #rclone:
            #                   condition: service_healthy
        ports:
            - 8096:8096
        group_add:
            - "303"
        networks:
            - jellyfin
        restart: unless-stopped

    ### media finders ###

    ### extra services
    frps:
        image: snowdreamtech/frps
        container_name: frps
        user: ${PUID}:${PGID}
        network_mode: host
        volumes:
            - ./frp:/etc/frp
        restart: unless-stopped

networks:
    arrs:
        driver: bridge
        ipam:
            config:
                - subnet: 10.125.0.0/24

    jellyfin:
        driver: bridge

    socket_proxy:
        name: socket_proxy
        driver: bridge
        ipam:
            config:
                - subnet: 172.16.224.0/24

    traefik:
        name: traefik
        driver: bridge
        ipam:
            config:
                - subnet: 10.255.224.0/24

include:
    - ./traefik/compose.yaml
    - ./socket-proxy/compose.yaml
