networks:
    arrs:
        driver: bridge
        ipam:
            config:
                - subnet: 10.125.0.0/24

    jellyfin:
        driver: bridge

    socket_proxy:
        name: socket_proxy
        driver: bridge

    socket_proxy_writable:
        name: socket_proxy_writable
        driver: bridge

    traefik-tailscale:
        name: traefik-tailscale
        driver: bridge

    traefik-external:
        name: traefik-external
        driver: bridge

# homepage is on root domain

include:
    # common
    - ../common/socket-proxy/compose.yaml

    # maybe not so common after all
    - ./watchtower/compose.yaml
    - ./traefik/compose.yaml

    - ./arrs/compose.yaml
    - ./downloader/compose.yaml
    - ./view/compose.yaml
    - ./frpc/compose.yaml
