services:
    homepage:
        image: gethomepage/homepage:latest
        container_name: homepage
        networks:
            - traefik
            - socket_proxy

        security_opt:
            - no-new-privileges:true
        pids_limit: 200
        environment:
            PUID: ${PUID}
            PGID: ${PGID}

            PROXY_SUBDOMAINS: ${PROXY_SUBDOMAINS:?}
            HOMEPAGE_ALLOWED_HOSTS: stuff.jjay.dev
        volumes:
            # NOTE: this is copied to /app/config by init.sh
            - ./config:/config # Make sure your local config directory exists
            - ./container/init.sh:/usr/local/bin/init.sh
            - ${APP_ROOT}/homepage/logs:/app/config/logs
        expose:
            - 3000
        entrypoint: ["/bin/sh", "/usr/local/bin/init.sh"]
        labels:
            traefik.enable: true
            traefik.http.routers.homepage-rtr.rule: Host(`${DOMAINNAME}`)
            traefik.http.routers.homepage-rtr.middlewares: middlewares-authentik@file,middlewares-error-pages@file
            traefik.http.routers.homepage-rtr.priority: 25
