services:
    actual-budget:
        image: actualbudget/actual-server:latest
        container_name: actual_budget
        restart: unless-stopped
        volumes:
            - ${APP_ROOT}/actual_budget/data:/data

        networks:
            - traefik-tailscale

        labels:
            traefik.enable: true

            expose.external: false

            treafik.http.routers.actual-budget-rtr.rule: Host(`budget.${INTERNAL_DOMAINNAME}`)

            homepage.group: internal
            homepage.name: Actual Budget
            homepage.icon: sh-actual-budget.svg
            homepage.href: https://budget.${INTERNAL_DOMAINNAME}
