services:
    # jellyseerr and jellyfin have custom themes--no themepark needed
    jellyseerr:
        image: fallenbagel/jellyseerr:latest
        container_name: jellyseerr
        user: ${PUID}:${PGID}
        environment:
            - LOG_LEVEL=info
            - TZ=${TZ:-Etc/UTC}
        expose:
            - 5055
        volumes:
            - ${APP_ROOT}/jellyseerr/app/config:/app/config
        networks:
            - traefik
            - jellyfin
            - arrs
        restart: unless-stopped
        labels:
            traefik.enable: true
            traefik.http.routers.jellyseerr-rtr.rule: Host(`jellyseerr.${DOMAINNAME}`)
            traefik.http.routers.jellyseerr-rtr.middlewares: middlewares-authentik@file

            homepage.group: media
            homepage.name: Jellyseer
            homepage.icon: sh-jellyseer.svg
            homepage.href: https://jellyseer.${DOMAINNAME}

    jellyfin:
        image: jellyfin/jellyfin
        container_name: jellyfin
        user: ${PUID}:${PGID}
        environment:
            - TZ=${TZ:-Etc/UTC}
            - JELLYFIN_PublishedServerUrl=https://${DOMAINNAME}
        volumes:
            - ${APP_ROOT}/jellyfin/config:/config
            - ${APP_ROOT}/jellyfin/cache:/cache
            - ${DATA_MOUNT_DIR}:/data
            - /dev/dri/renderD128:/dev/dri/renderD128
        depends_on: []
        expose:
            - 8096
        group_add:
            - "303"
        networks:
            - jellyfin
            - traefik
        restart: unless-stopped
        labels:
            traefik.enable: true
            traefik.http.routers.jellyfin-rtr.rule: Host(`jellyfin.${DOMAINNAME}`)

            homepage.group: media
            homepage.name: Jellyfin
            homepage.icon: sh-jellyfin.svg
            homepage.href: https://jellyfin.${DOMAINNAME}
