services:
    # jellyseerr and jellyfin have custom themes--no themepark needed
    jellyseerr:
        image: fallenbagel/jellyseerr:latest
        container_name: jellyseerr
        user: ${PUID}:${PGID}
        security_opt:
            - no-new-privileges:true
        pids_limit: 200
        environment:
            - LOG_LEVEL=info
            - TZ=${TZ:-Etc/UTC}
        expose:
            - 5055
        volumes:
            - ${APP_ROOT}/jellyseerr/app/config:/app/config
        networks:
            - traefik-external
            - jellyfin
            - arrs
        restart: unless-stopped
        labels:
            expose.external: true

            traefik.enable: true
            traefik.http.routers.jellyseerr-rtr.rule: Host(`jellyseerr.${DOMAINNAME}`)
            traefik.http.routers.jellyseerr-rtr.middlewares: middlewares-authentik@file

            homepage.group: media
            homepage.name: Jellyseerr
            homepage.icon: sh-jellyseerr.svg
            homepage.href: https://jellyseerr.${DOMAINNAME}

    jellyfin:
        image: jellyfin/jellyfin
        container_name: jellyfin
        security_opt:
            - no-new-privileges:true
        pids_limit: 200
        user: ${PUID}:${PGID}
        environment:
            - TZ=${TZ:-Etc/UTC}
            - JELLYFIN_PublishedServerUrl=https://jellyfin.${DOMAINNAME}
        volumes:
            - ${APP_ROOT}/jellyfin/config:/config
            - ${APP_ROOT}/jellyfin/cache:/cache
            - ${DATA_MOUNT_DIR}:/data
            - /dev/dri/renderD128:/dev/dri/renderD128
        depends_on: []
        expose:
            - 8096
        runtime: nvidia

        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [gpu]
        networks:
            - jellyfin
            - traefik-external
        restart: unless-stopped
        labels:
            expose.external: true

            traefik.enable: true
            traefik.http.routers.jellyfin-rtr.rule: Host(`jellyfin.${DOMAINNAME}`)

            homepage.group: media
            homepage.name: Jellyfin
            homepage.icon: sh-jellyfin.svg
            homepage.href: https://jellyfin.${DOMAINNAME}
