services:
    frps-internal:
        image: snowdreamtech/frps
        container_name: frps-internal
        user: ${PUID}:${PGID}
        networks:
            - traefik
        ports:
            - 7001:7000
        volumes:
            - ./config:/etc/frp
        restart: unless-stopped
        environment:
            FRP_OIDC_ISSUER: ${FRP_OIDC_ISSUER:?err}
            FRP_OIDC_AUDIENCE: ${FRP_OIDC_AUDIENCE:?err}

    frps-external:
        image: snowdreamtech/frps
        container_name: frps-external
        user: ${PUID}:${PGID}
        network_mode: host
        volumes:
            - ./config:/etc/frp
        restart: unless-stopped
        environment:
            FRP_OIDC_ISSUER: ${FRP_OIDC_ISSUER:?err}
            FRP_OIDC_AUDIENCE: ${FRP_OIDC_AUDIENCE:?err}
