services:
    sonarr:
        image: ghcr.io/linuxserver/sonarr:latest
        container_name: sonarr
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ:-Etc/UTC}
            - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:sonarr
            - TP_THEME=${TP_THEME}
        volumes:
            - ${APP_ROOT}/sonarr/config:/config
            - ${APP_ROOT}/sonarr/scripts:/scripts
            - ${DATA_MOUNT_DIR}:/data
        security_opt:
            - no-new-privileges:true
        pids_limit: 200
        depends_on: []
        expose:
            - 8989
        networks:
            - traefik
            - arrs
        restart: unless-stopped
        labels:
            traefik.enable: true
            traefik.http.routers.sonarr-rtr.rule: Host(`sonarr.${DOMAINNAME}`)
            traefik.http.routers.sonarr-rtr.middlewares: middlewares-authentik@file

            homepage.group: internal
            homepage.name: Sonarr
            homepage.icon: sh-sonarr.svg
            homepage.href: https://sonarr.${DOMAINNAME}

    radarr:
        image: linuxserver/radarr:latest
        container_name: radarr
        security_opt:
            - no-new-privileges:true
        pids_limit: 200
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ:-Etc/UTC}
            - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:radarr
            - TP_THEME=${TP_THEME}
        volumes:
            - ${APP_ROOT}/radarr/config:/config
            - ${APP_ROOT}/radarr/scripts:/scripts
            - ${DATA_MOUNT_DIR}:/data
        depends_on: []
        networks:
            - traefik
            - arrs
        expose:
            - 7676
        restart: unless-stopped
        labels:
            traefik.enable: true
            traefik.http.routers.radarr-rtr.rule: Host(`radarr.${DOMAINNAME}`)
            traefik.http.routers.radarr-rtr.middlewares: middlewares-authentik@file

            homepage.group: internal
            homepage.name: Radarr
            homepage.icon: sh-radarr.svg
            homepage.href: https://radarr.${DOMAINNAME}

    prowlarr:
        image: ghcr.io/linuxserver/prowlarr:latest
        container_name: prowlarr
        security_opt:
            - no-new-privileges:true
        pids_limit: 200
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ:-Etc/UTC}
            - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:prowlarr
            - TP_THEME=${TP_THEME}
        volumes:
            - ${APP_ROOT}/prowlarr/config:/config
        networks:
            - traefik
            - arrs
        expose:
            - 9696
        restart: unless-stopped
        labels:
            traefik.enable: true
            traefik.http.routers.prowlarr-rtr.rule: Host(`prowlarr.${DOMAINNAME}`)
            traefik.http.routers.prowlarr-rtr.middlewares: middlewares-authentik@file

            homepage.group: internal
            homepage.name: Prowlarr
            homepage.icon: sh-prowlarr.svg
            homepage.href: https://prowlarr.${DOMAINNAME}

    flaresolverr:
        image: flaresolverr/flaresolverr:latest
        container_name: flaresolverr
        user: ${PUID}:${PGID}
        security_opt:
            - no-new-privileges:true
        pids_limit: 200
        environment:
            - LOG_LEVEL=${LOG_LEVEL:-info}
            - LOG_HTML=${LOG_HTML:-false}
            - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
            - TZ=${TZ:-Etc/UTC}
        expose:
            - 8191
        networks:
            - traefik
            - arrs
        restart: unless-stopped
