services:
    uptime-kuma:
        image: louislam/uptime-kuma:latest
        container_name: uptime-kuma
        networks:
            - traefik
            - socket_proxy
        volumes:
            - ${APP_ROOT}/uptime-kuma/data:/app/data
        expose:
            - 3001
        restart: unless-stopped
        labels:
            traefik.enable: true
            traefik.http.routers.uptime-kuma-rtr.rule: Host(`uptime.${DOMAINNAME}`)
            traefik.http.routers.uptime-kuma-rtr.middlewares: middlewares-authentik@file

            homepage.group: stuff
            homepage.name: Uptime Kuma
            homepage.icon: sh-uptime-kuma.svg
            homepage.href: https://uptime.${DOMAINNAME}
            homepage.widget.type: uptimekuma
            homepage.widget.url: http://uptime-kuma:3001
            homepage.widget.slug: ${UPTIME_KUMA_SLUG:?err}
