services:
    uptime-kuma:
        image: louislam/uptime-kuma:latest
        container_name: uptime-kuma
        volumes:
            - ../${APP_ROOT}/uptime-kuma:/app/data
        expose:
            - 3001
        restart: unless-stopped
