services:
    actual-budget:
        image: actualbudget/actual-server:latest
        container_name: actual-budget
        user: ${PUID}:${PGID}
        pids_limit: 200
        security_opt:
            - no-new-privileges:true
        restart: unless-stopped
        volumes:
            - ${APP_ROOT}/actual_budget/data:/data

        networks:
            - traefik-external

        environment:
            ACTUAL_OPENID_DISCOVERY_URL: https://authentik.${ROOT_DOMAINNAME}
            ACTUAL_OPENID_CLIENT_ID: ${ACTUAL_BUDGET_OIDC_CLIENT_ID:?}
            ACTUAL_OPENID_CLIENT_SECRET: ${ACTUAL_BUDGET_OIDC_CLIENT_SECRET:?}
            ACTUAL_OPENID_SERVER_HOSTNAME: https://budget.${INTERNAL_DOMAINNAME}

            ACTUAL_TRUSTED_PROXIES: 0.0.0.0/0,::/0

        labels:
            traefik.enable: true

            expose.external: true

            traefik.http.routers.actual_budget-rtr.rule: Host(`budget.${DOMAINNAME}`)

            homepage.group: stuff
            homepage.name: Actual Budget
            homepage.icon: sh-actual-budget.svg
            homepage.href: https://budget.${DOMAINNAME}
