services:
    homepage:
        build:
            context: ./container
        container_name: homepage
        networks:
            - traefik
            - socket_proxy
        environment:
            PUID: ${PUID}
            PGID: ${PGID}
        volumes:
            # NOTE: this is copied to /app/config by init.sh
            - ./config:/config # Make sure your local config directory exists
            - ${APP_ROOT}/homepage/logs:/app/config/logs
        expose:
            - 3000
        labels:
            traefik.enable: true
            traefik.http.routers.homepage-rtr.rule: Host(`${DOMAINNAME}`)
            traefik.http.routers.homepage-rtr.middlewares: middlewares-authentik@file
