services:
    gluetun:
        image: qmcgaw/gluetun
        container_name: gluetun
        security_opt:
            - no-new-privileges:true
        pids_limit: 200
        cap_add:
            - NET_ADMIN
        devices:
            - /dev/net/tun:/dev/net/tun
        environment:
            - VPN_SERVICE_PROVIDER=${WIREGUARD_PROVIDER}

            - VPN_TYPE=wireguard
            - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
            - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
            - WIREGUARD_PRESHARED_KEY=${WIREGUARD_PRESHARED_KEY}

            # IMPORTANT FOR SPEEDS
            - SERVER_CITIES=${WIREGUARD_SERVER_CITIES}

            - FIREWALL_VPN_INPUT_PORTS=${TORRENT_PORT}
        networks:
            - arrs
            - traefik-tailscale
        expose:
            - 8080 # qbit
            - 6888 # aria2 RPC
            - 9081 # ariang
        labels:
            expose.external: false

            traefik.enable: true

            traefik.http.routers.qbittorrent-rtr.rule: Host(`qbit.${INTERNAL_DOMAINNAME}`)
            traefik.http.routers.qbittorrent-rtr.service: qbittorrent-svc
            traefik.http.services.qbittorrent-svc.loadbalancer.server.port: 8080

            traefik.http.routers.aria2-rpc-rtr.rule: Host(`aria.${INTERNAL_DOMAINNAME}`) && PathPrefix(`/jsonrpc`)
            traefik.http.routers.aria2-rpc-rtr.service: aria2-rpc-svc
            traefik.http.services.aria2-rpc-svc.loadbalancer.server.port: 6800

            traefik.http.routers.aria2-web-rtr.rule: Host(`aria.${INTERNAL_DOMAINNAME}`)
            traefik.http.routers.aria2-web-rtr.service: aria2-web-svc
            traefik.http.services.aria2-web-svc.loadbalancer.server.port: 9081

        restart: unless-stopped

include:
    - ./aria/compose.yaml
    - ./qbit/compose.yaml
