services:
    webtop:
        image: lscr.io/linuxserver/webtop:latest
        container_name: webtop
        security_opt:
            - no-new-privileges:true
        environment:
            - PUID
            - PGID
            - TZ
            - SUBFOLDER=/ #optional
            - TITLE=Webtop #optional
        volumes:
            - ${APP_ROOT}/webtop/data:/config
        expose:
            - 3000
        devices:
            - /dev/dri:/dev/dri #optional
        shm_size: "1gb" #optional
        restart: unless-stopped
        labels:
            traefik.enable: true
            traefik.http.routers.webtop-rtr.rule: Host(`webtop.${DOMAINNAME}`)
            traefik.http.routers.webtop-rtr.middlewares: middlewares-authentik@file
