services:
    well_known:
        image: caddy:latest
        container_name: well-known
        user: ${PUID}:${PGID}
        security_opt:
            - no-new-privileges:true
        pids_limit: 200
        restart: unless-stopped
        networks:
            - traefik
        expose:
            - 8080
        environment:
            DOMAINNAME: ${DOMAINNAME}
        volumes:
            - ./config/Caddyfile:/etc/caddy/Caddyfile
            - ./web:/www-template

            - ${APP_ROOT}/static/templates:/var/www

            - ./container/init.sh:/usr/local/bin/init.sh

        entrypoint: ["/bin/sh", "/usr/local/bin/init.sh"]

        labels:
            traefik.enable: true
            traefik.http.services.static-svc.loadbalancer.server.port: 8080
            traefik.http.routers.static-rtr.rule: Host(`${DOMAINNAME}`) && PathPrefix(`/.well-known`)
