http:
    routers:
        media-rtr:
            rule: HostRegexp(`^(.+\.)?media\.{{ env "DOMAINNAME" | regexQuoteMeta }}$`)
            entrypoints:
                - websecure
            service: media-svc
    services:
        media-svc:
            loadBalancer:
                servers:
                    - url: "http://frps-internal:9090"
