# ------------------------------
# -- Socket Proxy
# -- Updated 2024-June-04
# ------------------------------
name: socket-proxy # Project Name
services:
    socket-proxy:
        extends:
            file: ../../common/socket-proxy/compose.yaml
            service: socket-proxy
