networks:
  bridge_backend:
    driver: bridge

services:
  bridges-config:
    image: alpine:latest
    depends_on:
      discord-config:
        condition: service_completed_successfully

include:
  - ./discord/compose.yaml
