services:
    postgres:
        image: postgres:13-alpine
        restart: unless-stopped
        security_opt:
            - no-new-privileges:true
        pids_limit: 100
        user: ${PUID}:${PGID}
        read_only: true
        networks:
            - bridge_backend
        tmpfs:
            - /tmp
            - /var/run/postgresql
        environment:
            # timezone inside container
            TZ: ${TZ}

            # necessary Postgres options/variables
            POSTGRES_USER: bridge-user
            POSTGRES_PASSWORD: ${MATRIX_BRIDGE_PG_PASS}

            POSTGRES_INITDB_ARGS: --encoding=UTF-8 --lc-collate=C --lc-ctype=C

        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"
                ]
            start_period: 20s
            interval: 30s
            retries: 5
            timeout: 5s
