services:
    tailscale-exit-node:
        image: tailscale/tailscale:stable
        container_name: tailscale-exit-node
        user: ${PUID}:${PGID}
        environment:
            TS_EXTRA_ARGS: --advertise-tags=tag:internal --advertise-exit-node --login-server=https://headscale.${DOMAINNAME}
            TS_AUTHKEY: ${TAILSCALE_EXIT_NODE_PREAUTH_KEY}
            TS_HOSTNAME: outside
            TS_STATE_DIR: /var/lib/tailscale
            TS_USERSPACE: true
            HEADSCALE_HOST: headscale.${DOMAINNAME}
        volumes:
            - ${APP_ROOT}/tailscale/data:/var/lib/tailscale
            - ${APP_ROOT}/tailscale/cache:/var/cache/tailscale

        security_opt:
            - no-new-privileges:true
        pids_limit: 200

        depends_on:
            - headscale

        restart: unless-stopped
